namespace Stardom3Assistant;

internal static class DashboardHtml
{
    public const string Value = """
<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>明星志愿3 · 辅助助手</title>
  <style>
    :root{color-scheme:dark;--bg:#0d0f16;--panel:#171a25;--panel2:#1d2130;--line:#2b3042;--text:#f4f0e8;--muted:#9da4b8;--gold:#f4c56a;--pink:#ef7fa3;--good:#65d6a8;--blue:#7eb8ff;--base-font:17px}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 18% 0,#28213c 0,transparent 34%),var(--bg);color:var(--text);font:var(--base-font)/1.5 "Microsoft YaHei UI",sans-serif}body[data-font="small"]{--base-font:15px}body[data-font="large"]{--base-font:20px}
    main{max-width:1500px;margin:auto;padding:28px}.top{display:flex;gap:18px;align-items:end;justify-content:space-between;margin-bottom:18px}.top-side{display:grid;justify-items:end;gap:7px}h1{font-size:2em;margin:0;letter-spacing:.04em}.sub{color:var(--muted);margin-top:5px}.date{font-size:2em;font-weight:700;color:var(--gold);white-space:nowrap}.date small{font-size:.5em;color:var(--muted);margin-left:8px}.font-tools{display:flex;align-items:center;gap:4px;color:var(--muted);font-size:12px}.font-tools button{border:1px solid var(--line);background:#11141d;color:var(--muted);border-radius:7px;padding:3px 8px;cursor:pointer}.font-tools button.active{color:var(--gold);border-color:#f4c56a70;background:#f4c56a10}
    .bar,.card,.notice{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);box-shadow:0 16px 50px #0003;border-radius:14px}.bar{display:flex;gap:12px;align-items:center;padding:12px 15px;margin-bottom:14px}.dot{width:9px;height:9px;border-radius:50%;background:#777}.dot.on{background:var(--good);box-shadow:0 0 12px var(--good)}.status{flex:1}.controls{display:flex;gap:10px}input,select,button{font:inherit}input,select{background:#10131c;border:1px solid var(--line);color:var(--text);padding:8px 10px;border-radius:8px;outline:none}input{width:210px}.artist-toolbar{display:flex;align-items:center;gap:10px;padding:12px 15px;margin:0 0 14px}.artist-toolbar .field-help{color:var(--muted);font-size:.82em;margin-left:5px}.artist-toolbar .field-help b{color:var(--gold)}
    .tabs{display:flex;gap:6px;margin:0 0 16px;padding:5px;width:max-content;background:#11141d;border:1px solid var(--line);border-radius:12px}.tab{border:0;background:transparent;color:var(--muted);padding:9px 18px;border-radius:8px;cursor:pointer;font:inherit}.tab.active{background:var(--panel2);color:var(--text);box-shadow:0 2px 8px #0005}.count{margin-left:7px;padding:1px 6px;border-radius:10px;background:#ffffff12;font-size:11px}
    .card{overflow:auto}.empty{padding:70px 20px;text-align:center;color:var(--muted);font-size:16px}table{border-collapse:collapse;width:100%;min-width:1260px}th,td{padding:10px 11px;text-align:right;border-bottom:1px solid var(--line);white-space:nowrap}th{position:sticky;top:0;background:#202433;color:#b9bfd0;font-size:12px;z-index:2}th:nth-child(1),td:nth-child(1),th:nth-child(2),td:nth-child(2),th:nth-child(3),td:nth-child(3){text-align:left}tbody tr:hover{background:#ffffff08}.name{font-weight:700;font-size:15px}.tag,.pill{font-size:11px;padding:2px 7px;border-radius:10px}.tag{color:#17120a;background:var(--gold);margin-left:7px}.metric-hot{color:var(--pink)}
    .notice-page{display:grid;gap:24px}.section-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:10px}.section-head h2{margin:0;font-size:19px}.section-head p{margin:2px 0 0;color:var(--muted)}.notice-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:12px;align-items:start}.notice{padding:0;box-shadow:0 10px 30px #0002;overflow:hidden}.notice-top{display:flex;gap:10px;align-items:center;padding:16px;cursor:pointer;list-style:none}.notice-top::-webkit-details-marker{display:none}.notice-top:before{content:'›';font-size:24px;line-height:1;color:var(--gold);transition:transform .18s}.notice[open]>.notice-top:before{transform:rotate(90deg)}.notice[open]>.notice-top{border-bottom:1px solid var(--line)}.notice-title{font-size:17px;font-weight:700;flex:1}.notice-id{font-size:12px;color:var(--muted);font-family:Consolas,monospace}.notice-body{padding:0 16px 16px}.pill{background:#ffffff10;color:#cbd2e5}.pill.running{background:#65d6a820;color:var(--good)}.pill.waiting{background:#f4c56a20;color:var(--gold)}.notice-meta{display:flex;flex-wrap:wrap;gap:6px;margin:12px 0;color:var(--muted)}.notice-meta span{background:#10131c;border:1px solid #252a3a;padding:3px 7px;border-radius:6px}.notice-description{background:#10131c;border-left:3px solid var(--blue);border-radius:7px;padding:9px 11px;margin-bottom:12px;white-space:pre-line}.notice-description b,.role-description b{display:block;color:var(--muted);font-size:.78em;margin-bottom:3px}.notice-party{display:grid;grid-template-columns:1fr 1.35fr;gap:6px;margin-bottom:12px}.party-cell{background:#11141d;border:1px solid #252a3a;border-radius:8px;padding:7px 9px;min-width:0}.party-cell b{display:block;font-size:11px;color:var(--muted);font-weight:400;margin-bottom:2px}.party-cell span{display:block;font-size:13px;overflow-wrap:anywhere}.dates{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:12px}.date-cell{background:#11141d;border-radius:8px;padding:7px}.date-cell b{display:block;font-size:11px;color:var(--muted);font-weight:400}.date-cell span{font-size:12px}.roles{display:grid;gap:9px}.role{border-top:1px solid var(--line);padding-top:9px}.role-line{display:flex;gap:8px;align-items:center}.role-name{font-weight:700}.difficulty{color:var(--gold);font-size:12px}.assigned{margin-left:auto;color:var(--blue)}.requirements{font-size:12px;color:var(--muted);margin-top:3px;white-space:normal}.role-description{margin-top:7px;padding:8px 10px;background:#ffffff08;border-radius:7px;white-space:pre-line}.section-count{color:var(--gold);font-size:13px}footer{color:#70788e;text-align:center;padding:15px}
    .event-page{display:grid;gap:16px}.event-summary{padding:14px 16px;color:var(--muted)}.event-summary b{color:var(--gold)}.event-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.event-toolbar button,.fold-tools button{border:1px solid var(--line);background:#11141d;color:var(--muted);padding:8px 12px;border-radius:8px;cursor:pointer}.event-toolbar button:hover,.fold-tools button:hover{color:var(--text);border-color:#596078}.event-toolbar .spacer{flex:1}.event-toolbar select{min-width:170px}.signed-mark{font-size:11px;color:var(--gold);border:1px solid #f4c56a55;border-radius:10px;padding:2px 7px}.special-mark{font-size:11px;color:var(--pink);border:1px solid #ef7fa355;border-radius:10px;padding:2px 7px}.event-list{display:grid;gap:9px}.event-item{background:#11141d;border:1px solid #252a3a;border-radius:10px;padding:11px}.event-item-head{display:flex;align-items:center;gap:6px;flex-wrap:wrap;margin-bottom:6px}.event-number{font-family:Consolas,monospace;color:var(--gold)}.event-kind,.event-section,.event-time{font-size:11px;border-radius:9px;padding:2px 7px;background:#ffffff0c;color:var(--muted)}.event-time{color:var(--blue);background:#7eb8ff12}.event-text{white-space:pre-line;overflow-wrap:anywhere}.event-source{font-size:10px;color:#697186;margin-top:6px}.event-catalog{display:grid;gap:13px}.story-card{padding:0;overflow:hidden}.story-head{display:flex;gap:12px;align-items:center;padding:15px 17px;background:linear-gradient(110deg,#202536,#191d29);cursor:pointer;list-style:none;user-select:none}.story-head::-webkit-details-marker{display:none}.story-head:before{content:'›';font-size:24px;line-height:1;color:var(--gold);transition:transform .18s}.story-card[open]>.story-head:before{transform:rotate(90deg)}.story-card[open]>.story-head{border-bottom:1px solid var(--line)}.story-head>div{flex:1;min-width:0}.story-head h2{font-size:18px;margin:0;flex:1}.story-subject{color:var(--blue);font-size:12px;margin-bottom:2px}.story-events{padding:0 16px}.story-event{padding:13px 0}.story-event+.story-event{border-top:1px solid var(--line)}.story-event .event-item{background:transparent;border:0;border-radius:0;padding:0}.story-event .event-section{display:none}.event-loading{padding:55px;text-align:center;color:var(--muted)}.weekly-reminder{display:grid;gap:11px}.weekly-head{display:flex;align-items:end;justify-content:space-between;gap:16px;padding:2px 3px}.weekly-head h2{margin:0;font-size:20px}.weekly-head p{margin:3px 0 0;color:var(--muted);font-size:12px}.weekly-side{display:flex;align-items:center;gap:10px;flex-wrap:wrap;justify-content:flex-end}.fold-tools{display:flex;gap:5px}.fold-tools button{padding:5px 9px;font-size:12px}.reminder-groups{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;align-items:start}.reminder-card .story-events{max-height:560px;overflow:auto}.reminder-card .event-section{display:none}.weekly-empty{padding:65px 20px;text-align:center;color:var(--muted)}
    .company-page{display:grid;gap:16px}.company-kpis{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:12px}.company-kpi{padding:18px}.company-kpi span{display:block;color:var(--muted);font-size:.82em}.company-kpi b{display:block;margin-top:5px;color:var(--gold);font-size:1.45em}.company-section{padding:18px}.company-section h2{margin:0 0 12px}.inventory-table{min-width:720px}.inventory-table td:nth-child(4),.inventory-table th:nth-child(4){text-align:left;white-space:normal}.rotation-panel{padding:16px;display:grid;gap:11px}.rotation-title{display:flex;align-items:center;justify-content:space-between;gap:12px}.rotation-title h2{margin:0;font-size:1.15em}.rotation-source{color:var(--muted);font-size:.75em}.rotation-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.rotation-card{background:#11141d;border:1px solid #292f41;border-radius:10px;padding:12px}.rotation-card.next{border-color:#7eb8ff55}.rotation-card small{display:block;color:var(--muted)}.rotation-card b{display:block;color:var(--gold);font-size:1.2em;margin:3px 0}.rotation-card p{margin:0;color:var(--blue)}.notice-filter{display:flex;gap:10px;align-items:center;margin-bottom:14px}.notice-filter label{color:var(--muted)}
    /* 卡片内文字全部采用相对字号，随右上角字号设置同步缩放。 */
    .notice-title{font-size:1.08em}.notice-id,.difficulty,.requirements,.date-cell span,.party-cell span{font-size:.82em}.notice-meta,.notice-description,.role-description,.event-text{font-size:.92em}.notice-description b,.role-description b,.party-cell b,.date-cell b{font-size:.76em}.pill,.tag,.event-kind,.event-section,.event-time,.signed-mark,.special-mark{font-size:.74em}.section-count,.story-subject,.weekly-head p{font-size:.8em}.event-source{font-size:.7em}.story-head h2{font-size:1.12em}.weekly-head h2{font-size:1.25em}.fold-tools button{font-size:.8em}.notice-top:before,.story-head:before{font-size:1.55em}th{font-size:.78em}.name{font-size:1em}.font-tools{font-size:.78em}.font-tools button{font-size:1em}
    @media(max-width:900px){.reminder-groups{grid-template-columns:1fr}}@media(max-width:720px){main{padding:16px}.top{align-items:start;flex-direction:column}.top-side{justify-items:start}.bar{align-items:stretch;flex-wrap:wrap}.status{width:calc(100% - 30px)}.controls{width:100%}input{flex:1;width:auto}.tabs{width:100%;overflow:auto}.tab{flex:1;padding:9px;white-space:nowrap}.artist-toolbar{align-items:stretch;flex-direction:column}.artist-toolbar input{width:100%}.notice-grid,.rotation-grid{grid-template-columns:1fr}.notice-party,.dates{grid-template-columns:1fr}.weekly-head{align-items:start;flex-direction:column}.weekly-side{justify-content:flex-start}}
  </style>
</head>
<body><main>
  <div class="top"><div><h1>明星志愿3 · 辅助助手</h1><div class="sub">只读内存模式 · 不修改游戏数据</div></div><div class="top-side"><div class="date" id="date">等待游戏…</div><div class="font-tools"><span>字号</span><button data-font="small" onclick="setFontSize('small')">小</button><button data-font="medium" onclick="setFontSize('medium')">中</button><button data-font="large" onclick="setFontSize('large')">大</button></div></div></div>
  <div class="bar"><span class="dot" id="dot"></span><span class="status" id="status">正在连接 Stardom3.exe</span></div>
  <nav class="tabs"><button class="tab active" data-page="artists">艺人属性<span class="count" id="artistCount">0</span></button><button class="tab" data-page="company">公司概览<span class="count" id="itemCount">0</span></button><button class="tab" data-page="notices">通告<span class="count" id="noticeCount">0</span></button><button class="tab" data-page="reminders">本周提醒<span class="count" id="reminderCount">0</span></button><button class="tab" data-page="events">剧情<span class="count" id="eventCount">0</span></button></nav>
  <div class="card artist-toolbar" id="artistTools"><input id="search" placeholder="搜索艺人姓名或ID"><select id="scope"><option value="signed">仅签约艺人</option><option value="all">全部艺人</option></select></div>
  <div id="content"><div class="card"><div class="empty">请启动游戏并读取一个存档</div></div></div>
  <footer>数据每秒刷新 · 本工具仅申请 PROCESS_VM_READ 权限</footer>
</main>
<script>
const labels=[['favorability','好感度'],['acting','演技'],['eloquence','口才'],['singing','歌艺'],['fame','名气'],['demeanor','仪态'],['dynamics','动感'],['stamina','体能'],['intelligence','才智'],['confidence','自信'],['stress','压力'],['fatigue','疲劳'],['rebellious','叛逆'],['sexy','性感'],['affinity','亲和'],['popularity','人气'],['exposure','曝光'],['success','成功']];
let state=null,catalog=null,page='artists',eventArtist='',eventStory='all',eventQuery='',noticeCategory='all';const openNoticeCards=new Set();const $=id=>document.getElementById(id);$('search').oninput=render;$('scope').onchange=render;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{page=b.dataset.page;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x===b));$('artistTools').style.display=page==='artists'?'flex':'none';render()});
function setFontSize(size){const value=['small','medium','large'].includes(size)?size:'medium';document.body.dataset.font=value;document.querySelectorAll('.font-tools button').forEach(b=>b.classList.toggle('active',b.dataset.font===value));try{localStorage.setItem('stardom3-font-size',value)}catch{}}
try{setFontSize(localStorage.getItem('stardom3-font-size')||'medium')}catch{setFontSize('medium')}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){if(page==='events'){renderEvents();return}if(!state?.loaded){$('content').innerHTML=`<div class="card"><div class="empty">${esc(state?.message||'请启动游戏并读取一个存档')}</div></div>`;return}if(page==='reminders'){renderReminders();return}if(page==='company'){renderCompany();return}page==='artists'?renderArtists():renderNotices()}
function renderArtists(){const q=$('search').value.trim().toLowerCase(),signed=$('scope').value==='signed';let rows=state.artists.filter(a=>(!signed||a.isSigned)&&(!q||a.name.toLowerCase().includes(q)||String(a.id).includes(q)));
 const head=`<thead><tr><th>ID</th><th>艺人</th><th>性别</th>${labels.map(x=>`<th>${x[1]}</th>`).join('')}</tr></thead>`;
 const body=rows.map(a=>`<tr><td>${a.id}</td><td class="name">${esc(a.name)}${a.isSigned?'<span class="tag">签约</span>':''}</td><td>${a.sex}</td>${labels.map(([k])=>`<td class="${k==='stress'||k==='fatigue'?'metric-hot':''}">${a[k]??'—'}</td>`).join('')}</tr>`).join('');
 $('content').innerHTML=`<div class="card">${rows.length?`<table>${head}<tbody>${body}</tbody></table>`:'<div class="empty">没有符合条件的艺人</div>'}</div>`}
function money(value){return new Intl.NumberFormat('zh-CN').format(value??0)}
function renderCompany(){const c=state.company||{},items=c.items||[];const rows=items.map(i=>`<tr><td>${i.id}</td><td class="name">${esc(i.name)}</td><td>${esc(i.type)}</td><td>${esc(i.effect||'—')}</td><td>${i.count}</td></tr>`).join('');$('content').innerHTML=`<div class="company-page"><div class="company-kpis"><article class="card company-kpi"><span>公司</span><b>${esc(c.name||'翱翔天际')}</b></article><article class="card company-kpi"><span>当前资金</span><b>${money(c.money)}</b></article><article class="card company-kpi"><span>公司知名度</span><b>${money(c.fame)}</b></article><article class="card company-kpi"><span>已签约艺人</span><b>${c.signedArtistCount||0} 位</b></article></div><section class="card company-section"><h2>拥有的物品 <span class="section-count">${items.length} 种</span></h2>${rows?`<table class="inventory-table"><thead><tr><th>ID</th><th>物品</th><th>类型</th><th>效果</th><th>数量</th></tr></thead><tbody>${rows}</tbody></table>`:'<div class="empty">当前没有读取到持有物品</div>'}</section></div>`}
function rotationPanel(){const r=state.noticeRotation||{},card=(x,label,next)=>`<article class="rotation-card ${next?'next':''}"><small>${label} · ${esc(x?.startDate||'—')} ～ ${esc(x?.endDate||'—')}</small><b>${esc(x?.category||'—')}</b>${x?.detail?`<p>${esc(x.detail)}</p>`:''}</article>`;return `<section class="card rotation-panel"><div class="rotation-title"><h2>通告轮换</h2><span class="rotation-source">来源：${esc(r.source||'日程模板')}</span></div><div class="rotation-grid">${card(r.currentWeek,'本周',false)}${card(r.nextWeek,'下周',true)}</div></section>`}
function stateClass(s){return s==='进行中'?'running':s==='待结算'?'waiting':''}
function noticeCard(n,recruiting){const key=`${recruiting?'recruiting':'owned'}:${n.id}`,roles=(n.roles||[]).map(r=>`<div class="role"><div class="role-line"><span class="role-name">${esc(r.role)}</span><span class="difficulty">难度 ${r.difficulty}</span>${r.assignedArtist?`<span class="assigned">${esc(r.assignedArtist)}</span>`:recruiting?'<span class="assigned">待安排</span>':''}</div>${r.requirements?.length?`<div class="requirements">${r.requirements.map(esc).join(' · ')}</div>`:''}${r.description?`<div class="role-description"><b>角色内容</b>${esc(r.description)}</div>`:''}</div>`).join('');
 const producer=n.studio==='翱翔天際'?'玩家（自有公司） · 好感度不适用':n.producerName?`${esc(n.producerName)} · 好感度 ${n.producerFavorability ?? '—'}`:'—';
 return `<details class="notice" data-notice-key="${esc(key)}" ${openNoticeCards.has(key)?'open':''}><summary class="notice-top"><div class="notice-title">${esc(n.name)} <span class="notice-id">${esc(n.id)}</span></div><span class="pill">${esc(n.category)}</span><span class="pill ${stateClass(n.state)}">${esc(n.state)}</span></summary><div class="notice-body"><div class="notice-meta">${n.subtype?`<span>${esc(n.subtype)}</span>`:''}${n.className?`<span>${esc(n.className)}</span>`:''}</div><div class="notice-description"><b>内容简介</b>${esc(n.description||'暂无通告简介')}</div><div class="notice-party"><div class="party-cell"><b>制作公司</b><span>${esc(n.studio||'—')}</span></div><div class="party-cell"><b>制作人 / 好感度</b><span>${producer}</span></div></div><div class="dates"><div class="date-cell"><b>签约</b><span>${n.startDate||'—'}</span></div><div class="date-cell"><b>开工</b><span>${n.progressDate||'—'}</span></div><div class="date-cell"><b>完成</b><span>${n.endDate||'—'}</span></div></div><div class="roles">${roles||'<div class="requirements">暂无角色需求</div>'}</div></div></details>`}
function renderNotices(){const all=[...(state.currentNotices||[]),...(state.recruitingNotices||[])],types=[...new Set(all.map(n=>n.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'zh-CN'));if(noticeCategory!=='all'&&!types.includes(noticeCategory))noticeCategory='all';const match=n=>noticeCategory==='all'||n.category===noticeCategory,owned=(state.currentNotices||[]).filter(match),recruiting=(state.recruitingNotices||[]).filter(match);$('content').innerHTML=`<div class="notice-page">${rotationPanel()}<div class="notice-filter"><label for="noticeCategory">按类型筛选</label><select id="noticeCategory"><option value="all">全部类型（${all.length}）</option>${types.map(t=>`<option value="${esc(t)}" ${t===noticeCategory?'selected':''}>${esc(t)}（${all.filter(n=>n.category===t).length}）</option>`).join('')}</select></div><section><div class="section-head"><div><h2>当前拥有的通告</h2><p>仅显示有旗下艺人参与、尚未完全结束的通告</p></div><span class="section-count">${owned.length} 项</span></div><div class="notice-grid">${owned.length?owned.map(n=>noticeCard(n,false)).join(''):'<div class="card empty">当前筛选条件下没有持有通告</div>'}</div></section><section><div class="section-head"><div><h2>正在招人的通告</h2><p>来自各制作单位的当前邀约与角色条件</p></div><span class="section-count">${recruiting.length} 项</span></div><div class="notice-grid">${recruiting.length?recruiting.map(n=>noticeCard(n,true)).join(''):'<div class="card empty">当前筛选条件下没有招募通告</div>'}</div></section></div>`;$('noticeCategory').onchange=e=>{noticeCategory=e.target.value;renderNotices()};document.querySelectorAll('details.notice[data-notice-key]').forEach(card=>card.addEventListener('toggle',()=>{const key=card.dataset.noticeKey;if(card.open)openNoticeCards.add(key);else openNoticeCards.delete(key)}))}
function eventItem(e,weekly=false){const labels=weekly?[e.timeLabel]:[...new Set((e.windows||[]).map(w=>w.label))],source=weekly&&(!e.sourceLine||e.sourceLine<=0)?`日历提醒 · ${esc(e.artist)}`:`来源：FlySky日记 · ${esc(weekly?e.artist:eventArtist)} · 正文第 ${e.sourceLine} 行`;return `<article class="event-item"><div class="event-item-head"><span class="event-number">#${esc(e.id)}</span><span class="event-kind">${esc(e.kind)}</span><span class="event-section">${esc(e.section)}</span>${e.isRecruitment?'<span class="signed-mark">可签约</span>':''}${e.isSpecialEvent?'<span class="special-mark">特殊事件</span>':''}${labels.slice(0,2).map(x=>`<span class="event-time">${esc(x)}</span>`).join('')}</div><div class="event-text">${esc(e.text)}</div><div class="event-source">${source}</div></article>`}
function toggleCards(containerId,open){document.querySelectorAll(`#${containerId} details.story-card`).forEach(card=>card.open=open)}
function renderStoryGroups(items){const groups=Object.values(items.reduce((m,e)=>{(m[e.section]??={title:e.section,items:[]}).items.push(e);return m},{}));return groups.length?groups.map(g=>`<details class="card story-card"><summary class="story-head"><h2>${esc(g.title)}</h2><span class="section-count">${g.items.length} 条事件</span></summary><div class="story-events">${g.items.map(e=>`<div class="story-event">${eventItem(e)}</div>`).join('')}</div></details>`).join(''):'<div class="card empty">没有匹配的事件</div>'}
function renderWeeklyReminders(){
 const week=state?.weeklyEvents,events=week?.events||[],groups=Object.values(events.reduce((m,e)=>{const key=`${e.artist}\u0000${e.section}`;(m[key]??={artist:e.artist,section:e.section,items:[],isSpecial:e.isSpecialEvent,isRecruitment:e.isRecruitment}).items.push(e);return m},{}));
 const cards=groups.map(g=>`<details class="card story-card reminder-card"><summary class="story-head"><div><div class="story-subject">${esc(g.artist)}</div><h2>${esc(g.section)}</h2></div>${g.isSpecial?'<span class="special-mark">特殊事件</span>':g.isRecruitment?'<span class="signed-mark">可签约</span>':'<span class="signed-mark">已签约</span>'}<span class="section-count">${g.items.length} 条</span></summary><div class="story-events">${g.items.map(e=>`<div class="story-event">${eventItem(e,true)}</div>`).join('')}</div></details>`).join('');
 return `<section class="weekly-reminder"><div class="weekly-head"><div><h2>本周事件提醒</h2><p>按剧情归类；仅显示有明确时间限制的内容，仍需满足事件前置条件</p></div><div class="weekly-side"><span class="section-count">${week?.startDate||'—'} ～ ${week?.endDate||'—'} · ${groups.length} 个剧情 / ${events.length} 条</span><div class="fold-tools"><button onclick="toggleCards('reminderGroups',true)">全部展开</button><button onclick="toggleCards('reminderGroups',false)">全部收起</button></div></div></div><div class="reminder-groups" id="reminderGroups">${cards||'<div class="card weekly-empty">本周没有符合条件的限时剧情</div>'}</div></section>`
}
function renderReminders(){$('content').innerHTML=`<div class="event-page">${renderWeeklyReminders()}</div>`}
function renderEvents(){
 if(!catalog){$('content').innerHTML='<div class="card event-loading">正在载入 FlySky 全艺人事件资料…</div>';return}
 const subjects=[...(catalog.artists||[]).map(x=>({...x,isSpecial:false})),...(catalog.specialEvents||[]).map(x=>({...x,isSpecial:true}))];
 if(!eventArtist)eventArtist=subjects[0]?.name||'';
 const artist=subjects.find(a=>a.name===eventArtist)||subjects[0],stories=[...new Set((artist?.events||[]).map(e=>e.section))];
 if(eventStory!=='all'&&!stories.includes(eventStory))eventStory='all';
 const filterItems=()=>{const q=eventQuery.trim().toLowerCase();return (artist?.events||[]).filter(e=>(eventStory==='all'||e.section===eventStory)&&(!q||`${e.id} ${e.kind} ${e.section} ${e.text}`.toLowerCase().includes(q)))},items=filterItems();
 const options=groups=>groups.map(a=>`<option value="${esc(a.name)}" ${a.name===eventArtist?'selected':''}>${esc(a.name)}（${a.eventCount}）</option>`).join('');
 const totalLabel=`共 ${catalog.artistCount} 位艺人 + ${catalog.specialCount||0} 类特殊事件 / ${catalog.eventCount} 条`;
 $('content').innerHTML=`<div class="event-page"><div class="event-toolbar"><select id="eventArtist" aria-label="选择艺人或特殊事件"><optgroup label="艺人事件">${options(catalog.artists||[])}</optgroup><optgroup label="特殊事件">${options(catalog.specialEvents||[])}</optgroup></select><select id="eventStory" aria-label="选择剧情"><option value="all">全部剧情（${stories.length} 类）</option>${stories.map(s=>`<option value="${esc(s)}" ${s===eventStory?'selected':''}>${esc(s)}</option>`).join('')}</select><input id="eventSearch" value="${esc(eventQuery)}" placeholder="搜索事件内容"><div class="fold-tools"><button onclick="toggleCards('eventCatalog',true)">全部展开</button><button onclick="toggleCards('eventCatalog',false)">全部收起</button></div><span class="spacer"></span><span class="section-count" id="eventResultCount">当前 ${items.length} 条 · ${totalLabel}</span></div><div class="event-catalog" id="eventCatalog">${renderStoryGroups(items)}</div></div>`;
 const refreshEventResults=()=>{const found=filterItems();document.querySelector('.event-catalog').innerHTML=renderStoryGroups(found);$('eventResultCount').textContent=`当前 ${found.length} 条 · ${totalLabel}`};
 $('eventArtist').onchange=e=>{eventArtist=e.target.value;eventStory='all';renderEvents()};$('eventStory').onchange=e=>{eventStory=e.target.value;refreshEventResults()};$('eventSearch').oninput=e=>{eventQuery=e.target.value;refreshEventResults()}
}
async function loadCatalog(){try{const r=await fetch('/api/events',{cache:'no-store'});catalog=await r.json();$('eventCount').textContent=catalog.eventCount||0;if(page==='events')render()}catch{catalog=null}}
function reminderSignature(value){return `${value?.date||''}|${(value?.artists||[]).filter(a=>a.isSigned).map(a=>a.id).join(',')}|${(value?.weeklyEvents?.events||[]).map(e=>`${e.artist}:${e.id}:${e.isRecruitment}:${e.isSpecialEvent}`).join(',')}`}
async function poll(){try{const previous=reminderSignature(state),r=await fetch('/api/state',{cache:'no-store'});state=await r.json();$('dot').className='dot '+(state.connected?'on':'');$('status').textContent=state.loaded?`已连接游戏（PID ${state.processId}）· 数据实时刷新中`:state.message;$('date').innerHTML=state.date?`${state.date}<small>${state.weekday}</small>`:'等待游戏…';$('artistCount').textContent=state.artists?.filter(a=>a.isSigned).length||0;$('itemCount').textContent=state.company?.items?.length||0;$('noticeCount').textContent=(state.currentNotices?.length||0)+(state.recruitingNotices?.length||0);$('reminderCount').textContent=state.weeklyEvents?.eventCount||0;$('eventCount').textContent=catalog?.eventCount||0;const changed=previous!==reminderSignature(state);if(page==='reminders'?changed:page!=='events')render()}catch{$('dot').className='dot';$('status').textContent='助手服务连接中断'}setTimeout(poll,1000)}loadCatalog();poll();
</script></body></html>
""";
}
